# Generated by Django 4.0.3 on 2022-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(default='Transparente', max_length=25)),
                ('altura', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('es_artesanal', models.BooleanField(default=False)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('creado', models.DateField(auto_now_add=True)),
                ('editado', models.DateField(auto_now=True)),
            ],
        ),
    ]
