# Generated by Django 4.0.3 on 2022-03-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social_profile',
            field=models.CharField(max_length=255),
        ),
    ]
